return {
    ["EASTEREXP"] = "20 minutes of 2x Experience",
    ["fudd10"] = "$1",
    ["fudd10_V2"] = "$2",
    ["Chandler"] = "$0",
    ["BIGNEWS"] = "Unlocks the title Big News.",
    ["KITT_RESET"] = "Free Stat Reset",
    ["Sub2UncleKizaru"] = "Free Stat Reset",
    ["SUB2GAMERROBOT_RESET1"] = "Free Stat Reset",
    ["Sub2Fer999"] = "20 minutes of 2x Experience",
    ["Enyu_is_Pro"] = "20 minutes of 2x Experience",
    ["JCWK"] = "20 minutes of 2x Experience",
    ["StarcodeHEO"] = "20 minutes of 2x Experience",
    ["MagicBUS"] = "20 minutes of 2x Experience",
    ["KittGaming"] = "20 minutes of 2x Experience",
    ["Sub2CaptainMaui"] = "20 minutes of 2x Experience",
    ["Sub2OfficialNoobie"] = "20 minutes of 2x Experience",
    ["TheGreatAce"] = "20 minutes of 2x Experience",
    ["Sub2NoobMaster123"] = "20 minutes of 2x Experience",
    ["Sub2Daigrock"] = "20 minutes of 2x Experience",
    ["Axiore"] = "20 minutes of 2x Experience",
    ["StrawHatMaine"] = "20 minutes of 2x Experience",
    ["TantaiGaming"] = "20 minutes of 2x Experience",
    ["Bluxxy"] = "20 minutes of 2x Experience",
    ["SUB2GAMERROBOT_EXP1"] = "30 minutes of 2x Experience",
}
